services:
  # --- GATEWAY PRINCIPALE ---
  healthai-api:
    build: ./healthai-api
    ports:
      - "8000:8000"
    env_file:
      - ./healthai-api/.env
    # Montage du dossier src local vers le dossier app dans le conteneur
    volumes:
      - ./healthai-api/src:/app/src
    # Force le rechargement automatique du serveur au changement de code
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    depends_on:
      - healthai-vision
      - healthai-workout
      - postgres
    networks:
      - internal

  # --- SERVICE VISION ---
  healthai-vision:
    build: ./healthai-vision
    ports:
      - "${HEALTHAI_VISION_PORT:-8001}:8001"
    env_file:
      - ./healthai-vision/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - MONGODB_URL=${MONGODB_URL:-mongodb://mongo:27017}
      - HF_MODEL_NAME=${HF_MODEL_NAME:-yolov8n.pt}
      - HF_CACHE_DIR=/app/.hf_cache
    volumes:
      - ./healthai-vision/src:/app/src
      - hf_cache:/app/.hf_cache
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
        "--reload",
      ]
    depends_on:
      - postgres
    networks:
      - internal

  # --- SERVICE WORKOUT ---
  healthai-workout:
    build: ./healthai-workout
    ports:
      - "${HEALTHAI_WORKOUT_PORT:-8002}:8002"
    env_file:
      - ./healthai-workout/.env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://healthai:healthai@postgres:5432/healthai_db}
      - MONGODB_URL=${MONGODB_URL:-mongodb://mongo:27017}
    volumes:
      - ./healthai-workout/src:/app/src
      - ./healthai-workout/models:/app/models
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8002",
        "--reload",
      ]
    depends_on:
      - postgres
      - mongo
    networks:
      - internal

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: healthai
      POSTGRES_PASSWORD: healthai
      POSTGRES_DB: healthai_db
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d:ro
      - pg-data:/var/lib/postgresql/data #
    networks:
      - internal

volumes:
  mongo-data:
  pg-data:
  hf_cache:

networks:
  internal:
    driver: bridge
